version: '2'
services:
    auth-service:
        build:
            context: ./auth-service
        environment:
            NODE_ENV: production
        depends_on:
            - db
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - auth-service
        volumes: 
            - "./auth-service/media:/media"
            - "./logs/nginx:/tmp/logs"
        ports:
            - "80:80"
            - "443:443"
