FROM couchdb:3.1.2

WORKDIR /

COPY etc/* /opt/couchdb/etc/
COPY config/fielddb_debug* /opt/couchdb/etc/

RUN set +x; \
  curl -X PUT http://admin:none@127.0.0.1:5984/_users; \
  curl -X PUT http://admin:none@127.0.0.1:5984/_replicator; \
  ls -alt /opt/couchdb/etc; \
  cat /opt/couchdb/etc/local.ini; \
  ls /opt/couchdb/etc/local.d;

# COPY fielddb_debug.* /usr/local/etc/couchdb
