version: '2'
services:
    db:
        ports:
          - "5984:5984"
    auth-service:
        build: ./auth-service
        working_dir: /auth-service
        command: npm run develop
        volumes:
            - ./auth-service:/auth-service
            - ./auth-service/media:/media
        ports:
            - "3183:3183"
        environment:
            NODE_ENV: development
        depends_on:
            - db
