#!/bin/bash

cd $FIELDDB_HOME/AuthenticationWebService


forever \
start \
-al $FIELDDB_HOME/logs/fielddbauth.log \
-ao $FIELDDB_HOME/logs/fielddbauthout.log \
-ae $FIELDDB_HOME/logs/fielddbautherr.log \
auth_service.js
