[httpd]
enable_cors = true

[cors]
origins = *
credentials = true

[couchdb]
single_node=true

[admins]
; by default for devs we use admin:none to simulate a non-admin party server:
admin = -pbkdf2-3f04b4318f9a5b3c20ff99fa9194744d0cffa603,e5fbfb69d2a5db31325d23462c43c7ea,10

[replicator]
auth_plugins = couch_replicator_auth_noop

[ssl]
enable = true
cert_file = /opt/couchdb/etc/fielddb_debug.crt
key_file = /opt/couchdb/etc/fielddb_debug.key